[colors]
background = '#24273a'
foreground = '#cad3f5'

cursor_bg = '#b7bdf8'
cursor_fg = '#24273a'
cursor_border = '#b7bdf8'

selection_bg = '#3e437e'
selection_fg = '#cad3f5'

ansi = ['#1e2030', '#ff7295', '#7cf891', '#ffd872', '#a1a8eb', '#3b4072', '#b7bdf8', '#eff1ff']
brights = ['#9596a1', '#ff9fb7', '#a5ffb5', '#ffe6a5', '#c6cbff', '#d0d4ff', '#e0e3ff', '#f8f9ff']
