# Kanagawa Theme

[manager]
cwd = { fg = "#8bd5ca" }

# Hovered
hovered = { fg = "#16161D", bg = "#E6C384" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#E6C384", italic = true }
find_position = { fg = "#D27E99", bg = "reset", italic = true }

# Marker
marker_copied = { fg = "#76946A", bg = "#76946A" }
marker_cut = { fg = "#C34043", bg = "#C34043" }
marker_selected = { fg = "#DCA561", bg = "#DCA561" }

# Tab
tab_active = { fg = "#16161D", bg = "#E6C384" }
tab_inactive = { fg = "#E6C384", bg = "#1F1F28" }
tab_width = 1

# Count
count_copied = { fg = "#1F1F28", bg = "#76946A" }
count_cut = { fg = "#1F1F28", bg = "#c34043" }
count_selected = { fg = "#1F1F28", bg = "#DCA561" }

# Border
border_symbol = "│"
border_style = { fg = "#E6C384" }

# Highlighting
syntect_theme = "~/.config/yazi/kanagawa.tmTheme"

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#2d4f67", bg = "#2d4f67" }

# Mode
mode_normal = { fg = "#1F1F28", bg = "#E6C384", bold = true }
mode_select = { fg = "#1F1F28", bg = "#76946A", bold = true }
mode_unset = { fg = "#1F1F28", bg = "#e46876", bold = true }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8aadf4", bg = "#494d64" }
progress_error = { fg = "#ed8796", bg = "#494d64" }

# Permissions
permissions_t = { fg = "#8aadf4" }
permissions_r = { fg = "#eed49f" }
permissions_w = { fg = "#ed8796" }
permissions_x = { fg = "#a6da95" }
permissions_s = { fg = "#8087a2" }

[input]
border = { fg = "#E6C384" }
title = {}
value = {}
selected = { reversed = true }

[select]
border = { fg = "#8aadf4" }
active = { fg = "#f5bde6" }
inactive = {}

[tasks]
border = { fg = "#8aadf4" }
title = {}
hovered = { underline = true }

[which]
mask = { bg = "#363a4f" }
cand = { fg = "#8bd5ca" }
rest = { fg = "#939ab7" }
desc = { fg = "#f5bde6" }
separator = "  "
separator_style = { fg = "#5b6078" }

[help]
on = { fg = "#f5bde6" }
exec = { fg = "#8bd5ca" }
desc = { fg = "#939ab7" }
hovered = { bg = "#5b6078", bold = true }
footer = { fg = "#494d64", bg = "#cad3f5" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#6A9589" },

	# Videos
	{ mime = "video/*", fg = "#76946A" },
	{ mime = "audio/*", fg = "#76946A" },

	# Archives
	{ mime = "application/zip", fg = "#938AA9" },
	{ mime = "application/gzip", fg = "#938AA9" },
	{ mime = "application/x-tar", fg = "#938AA9" },
	{ mime = "application/x-bzip", fg = "#938AA9" },
	{ mime = "application/x-bzip2", fg = "#938AA9" },
	{ mime = "application/x-7z-compressed", fg = "#938AA9" },
	{ mime = "application/x-rar", fg = "#938AA9" },

	# Fallback
	{ name = "*", fg = "#E6C384" },
	{ name = "*/", fg = "#DCD7BA" },
]
